(function(){
  const intro=`<h2>Introdução</h2><p>A aprovação em um concurso público costuma ser vista como algo reservado para pessoas extremamente inteligentes ou para quem pode estudar o dia inteiro. Essa percepção, embora comum, está distante da realidade.</p><p>Todos os anos, milhares de candidatos são aprovados conciliando trabalho, família, responsabilidades pessoais e apenas algumas horas de estudo por dia. O que diferencia esses candidatos não é um talento extraordinário, mas a capacidade de construir um método consistente, disciplinado e sustentável.</p><p>O propósito deste livro é justamente apresentar esse método.</p><p>Ao longo dos próximos capítulos, o estudante encontrará estratégias para organizar seus estudos, compreender o estilo da banca VUNESP, revisar de forma eficiente e transformar o conhecimento adquirido em desempenho na prova.</p><p>Este não é apenas um manual de estudos. É um projeto de preparação.</p>`;
  function coursePage(){
    const progress=AppStorage.load('progress');
    const modules=CourseData.modules.map((m,i)=>`<article class="module ${i===0?'open':''}"><button class="module-header" data-action="toggle-module"><span class="module-number">M${String(m.id).padStart(2,'0')}</span><span class="module-title"><strong>${m.title}</strong><span>${m.chapters?`${m.chapters.length} capítulos`:'Conteúdo será disponibilizado em breve'}</span></span><span class="badge ${m.status==='available'?'success':'warning'}">${m.status==='available'?'Disponível':'Em desenvolvimento'}</span><span>⌄</span></button>${m.chapters?`<div class="chapter-list">${m.chapters.map((c,j)=>`<a class="chapter-row" href="capitulo.html?id=${j+1}"><span class="chapter-check">${progress.completedChapters.includes(j+1)?'✓':''}</span><span><b>Capítulo ${j+1}</b> — ${c}</span><small>${j<2?'Disponível':'Em breve'}</small></a>`).join('')}</div>`:''}</article>`).join('');
    return heading('Meu curso','Uma trilha progressiva: método, conteúdo, prática e revisão.')+`<div class="card" style="margin-bottom:18px"><div class="card-header"><div><h2>Módulo atual</h2><span class="card-subtitle">Método e planejamento</span></div><b>${progress.completedChapters.length}/10 capítulos</b></div><div class="progress"><i style="width:${progress.completedChapters.length*10}%"></i></div></div><section class="module-list">${modules}</section>`;
  }
  function chapterPage(){
    const id=Number(new URLSearchParams(location.search).get('id')||1);
    if(id>2)return heading(`Capítulo ${id}`,'Conteúdo em desenvolvimento.')+`<div class="card empty-state"><b>Este capítulo está sendo preparado.</b><p>A estrutura já está pronta para receber o conteúdo completo.</p><a class="button button-primary" href="curso.html">Voltar ao curso</a></div>`;
    return id===2?chapter2():chapter1();
  }
  function chapter1(){
    const sections=CourseData.chapter1Sections.map((s,i)=>`<section><h2>${i+1}. ${s[0]}</h2><p>${s[1]}</p>${i===2?comparison():''}${i===8?flows():''}</section>`).join('');
    const fields=['Meu objetivo é:','Por que desejo essa aprovação?','O que estou disposto a fazer diariamente?','Quais distrações preciso eliminar?','Qual será meu horário fixo de estudos?'];
    const reflections=AppStorage.load('reflections');
    return `<article class="chapter-reader"><div class="chapter-hero"><span class="eyebrow light">Módulo 0 • Capítulo 1</span><h1>O Projeto Aprovação</h1><p>Aprovação não é sorte. É um sistema.</p><blockquote>“Quem vence um concurso não é, necessariamente, quem estudou mais. É quem estudou melhor durante mais tempo.”</blockquote></div><div class="chapter-content">${intro}${sections}<div class="reflection-grid">${fields.map((f,i)=>`<div class="form-group"><label for="reflection-${i}">${f}</label><textarea class="textarea reflection" id="reflection-${i}" data-key="q${i}" placeholder="Escreva sua resposta…">${Navigation.escapeText(reflections[`q${i}`]||'')}</textarea></div>`).join('')}<span class="save-status" id="reflection-status">As respostas são salvas automaticamente.</span></div><div class="button-row" style="margin-top:30px"><button class="button button-primary" data-action="complete-chapter" data-id="1">Marcar como concluído</button><a class="button button-secondary" href="capitulo.html?id=2">Próximo capítulo →</a></div></div></article>`;
  }
  function chapter2(){const qs=QuestionsData.slice(0,5).map(q=>window.Quiz.renderQuestion(q)).join('');return `<article class="chapter-reader"><div class="chapter-hero"><span class="eyebrow light">Módulo 0 • Capítulo 2</span><h1>Conhecendo a VUNESP</h1><p>Estudar a banca é tão importante quanto estudar a matéria.</p></div><div class="chapter-content">${['O que é a VUNESP','A diferença entre saber a matéria e saber fazer a prova','Perfil geral das questões','O comando da questão','Alternativas parcialmente corretas','Palavras absolutas','Português na VUNESP','Matemática e raciocínio','Informática','Conhecimentos específicos e rotina administrativa','A questão mais adequada','Como treinar para o padrão da banca','Os quatro tipos de erro','Método de leitura em três etapas','Gestão do tempo','Quando deixar uma questão para depois','O perigo de alterar respostas','Estudo antes da publicação do edital','Checklist de análise de questões','Atividade prática'].map((t,i)=>`<h2>${i+1}. ${t}</h2><p>${chapter2Text(i)}</p>`).join('')}<h2>21. Exercícios de fixação</h2><div id="chapter-quiz">${qs}</div><h2>22. Resumo</h2><p>Conhecer o estilo da banca melhora leitura, decisão e gestão do tempo. O edital é a referência oficial; questões e correções transformam teoria em desempenho.</p><h2>23. Registro pessoal</h2><p>Registre os padrões de erro que apareceram nos exercícios e defina uma ação concreta para a próxima sessão.</p><h2>24. Tarefa do capítulo</h2><p>Resolva vinte questões cronometradas, classifique cada erro e revise os pontos de conteúdo identificados.</p><button class="button button-primary" data-action="complete-chapter" data-id="2">Marcar como concluído</button></div></article>`}
  function chapter2Text(i){const texts=['A Fundação VUNESP organiza concursos e avaliações. Para o candidato, importa compreender como seus enunciados, alternativas e critérios transformam conteúdo em decisão.','Dominar um tema não garante acerto se o comando for lido com pressa. Treino de prova combina conhecimento, interpretação e estratégia.','As questões tendem a apresentar contexto objetivo e alternativas plausíveis. A precisão de leitura costuma separar a resposta integralmente correta das demais.','Circule mentalmente termos como correto, incorreto, exceto e mais adequado. Eles definem exatamente o que deve ser procurado.','Uma opção pode afirmar algo verdadeiro e ainda assim não responder por inteiro ao comando. Compare cada alternativa com a pergunta completa.','Termos como sempre, nunca, somente e exclusivamente exigem atenção. Não são automaticamente falsos, mas ampliam a afirmação e precisam de base.','Interpretação, relações de sentido e norma-padrão pedem leitura contextual. Volte ao trecho antes de escolher.','Organize dados, identifique a operação e estime o resultado. O cálculo deve confirmar um raciocínio já estruturado.','Priorize conceitos práticos: segurança, sistemas operacionais, editor de texto, planilhas e uso responsável de recursos digitais.','Relacione princípios e procedimentos às situações de atendimento, documentos, arquivos, ética e organização do trabalho.','Quando o comando pedir a opção mais adequada, compare completude, contexto e consequência; não procure apenas uma frase isoladamente verdadeira.','Treine em blocos cronometrados, corrija logo depois e classifique cada erro. O padrão dos erros orienta a revisão.','Use quatro categorias iniciais: conteúdo, interpretação, desatenção e estratégia. O caderno pode detalhar cálculo e falta de tempo.','Leia primeiro o comando, depois o texto-base e por fim as alternativas. Essa ordem dá propósito à leitura.','Reserve tempo para resolução, questões marcadas e cartão de respostas. Controle por blocos, sem consultar o relógio a cada minuto.','Adie quando não houver caminho claro após leitura cuidadosa. Marque a questão e preserve tempo para pontos mais acessíveis.','Só altere uma resposta com evidência concreta: regra lembrada, dado relido ou erro de cálculo identificado. Insegurança isolada não basta.','Antes do edital, fortaleça matérias estáveis e o método. Após a publicação, ajuste prioridades ao conteúdo e aos pesos oficiais.','Confira comando, palavras-chave, unidade, negação, abrangência e se a alternativa responde por completo.','Selecione uma prova semelhante, identifique dez comandos e classifique as armadilhas das alternativas.'];return texts[i]}
  function comparison(){return `<div class="comparison"><article><span class="badge">Candidato A</span><strong>20h/semana</strong><ul><li>10h no sábado</li><li>10h no domingo</li><li>Sem estudo durante a semana</li></ul></article><article class="recommended"><span class="badge success">Candidato B</span><strong>16h/semana</strong><ul><li>2h de segunda a sexta</li><li>4h no sábado</li><li>2h no domingo</li></ul><p class="callout">A frequência e a repetição distribuída tendem a ser mais sustentáveis que a concentração extrema.</p></article></div>`}
  function flows(){return `<p class="callout"><b>Modelo inadequado</b></p><div class="flow"><span>Teoria</span><b>→</b><span>Mais teoria</span><b>→</b><span>Medo de questões</span><b>→</b><span>Esquecimento</span><b>→</b><span>Recomeçar</span></div><p class="callout"><b>Modelo recomendado</b></p><div class="flow"><span>Teoria</span><b>→</b><span>Questões</span><b>→</b><span>Correção</span><b>→</b><span>Revisão</span><b>→</b><span>Novas questões</span><b>→</b><span>Consolidação</span></div>`}
  function reviewsPage(){const reviews=AppStorage.load('reviews');const today=new Date().toISOString().slice(0,10);const rows=reviews.map(r=>`<tr><td>${r.title}</td><td>${r.interval}</td><td>${new Date(r.due).toLocaleDateString('pt-BR')}</td><td><span class="badge ${r.status==='concluída'?'success':r.due<today?'danger':'warning'}">${r.status}</span></td><td><button data-action="review-complete" data-id="${r.id}">Concluir</button> <button data-action="review-delay" data-id="${r.id}">Adiar</button> <button data-action="review-cancel" data-id="${r.id}">Cancelar</button></td></tr>`).join('');return heading('Revisões espaçadas','Retome o conteúdo no momento certo: 24 horas, 7 dias e 30 dias.')+`<div class="grid grid-4">${stat(reviews.filter(r=>r.due===today&&r.status==='pendente').length,'Hoje'),stat(reviews.filter(r=>r.due<today&&r.status==='pendente').length,'Atrasadas'),stat(reviews.filter(r=>r.due>today&&r.status==='pendente').length,'Próximas'),stat(reviews.filter(r=>r.status==='concluída').length,'Concluídas')}</div><div class="card" style="margin-top:18px">${reviews.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Conteúdo</th><th>Ciclo</th><th>Data</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="empty-state"><b>Nenhuma revisão programada.</b><p>Conclua um capítulo para gerar automaticamente as revisões.</p><a class="button button-primary" href="curso.html">Ir para o curso</a></div>`}</div>`}
  function heading(t,p){return `<div class="page-heading"><div><span class="eyebrow">Projeto Aprovação</span><h1>${t}</h1><p>${p}</p></div></div>`}function stat(n,l){return `<div class="card stat-card"><span class="stat-icon">↻</span><div><b>${n}</b><span>${l}</span></div></div>`}
  window.Course={coursePage,chapterPage,reviewsPage};
})();
