(function(){
  let list=[],index=0,flipped=false;
  function page(){const disciplines=[...new Set(FlashcardsData.map(x=>x.discipline))];return `<div class="page-heading"><div><span class="eyebrow">Repetição ativa</span><h1>Flashcards</h1><p>Recupere a informação e classifique a dificuldade para orientar a próxima revisão.</p></div></div><div class="card"><div class="filters"><select class="select" id="flash-filter"><option value="">Todas as disciplinas</option>${disciplines.map(d=>`<option>${d}</option>`).join('')}</select><button class="button button-secondary" data-action="shuffle-flashcards">Embaralhar</button></div><div id="flash-stage"></div></div>`}
  function init(){list=[...FlashcardsData];index=0;render()}
  function render(){const host=document.getElementById('flash-stage');if(!host||!list.length)return;const c=list[index];const state=AppStorage.load('flashcards')[c.id]||{};host.innerHTML=`<div class="flashcard-stage"><p class="card-subtitle" style="text-align:center">${index+1} de ${list.length} • ${c.discipline}</p><div class="flashcard ${flipped?'flipped':''}" data-action="flip-card" tabindex="0" role="button" aria-label="Virar cartão"><div class="flashcard-inner"><div class="flash-face"><div><span class="eyebrow light">Frente</span><strong>${c.front}</strong><small style="display:block;margin-top:18px;color:#bdd0de">Clique para revelar</small></div></div><div class="flash-face back"><div><span class="eyebrow">Verso</span><strong>${c.back}</strong></div></div></div></div><div class="flash-actions"><button class="button button-secondary" data-action="flash-prev">← Voltar</button><button class="button button-danger" data-action="rate-card" data-rate="Difícil">Difícil</button><button class="button button-secondary" data-action="rate-card" data-rate="Médio">Médio</button><button class="button button-primary" data-action="rate-card" data-rate="Fácil">Fácil</button><button class="button button-secondary" data-action="flash-next">Avançar →</button></div><p class="save-status" style="text-align:center;margin-top:10px">${state.lastReview?`Última revisão: ${new Date(state.lastReview).toLocaleDateString('pt-BR')}`:'Ainda não revisado'}</p></div>`}
  function flip(){flipped=!flipped;render()}function move(d){index=(index+d+list.length)%list.length;flipped=false;render()}function rate(rate){const c=list[index];const days=rate==='Fácil'?7:rate==='Médio'?3:1;const next=new Date();next.setDate(next.getDate()+days);AppStorage.update('flashcards',s=>({...s,[c.id]:{lastReview:new Date().toISOString(),nextReview:next.toISOString(),correct:(s[c.id]?.correct||0)+(rate==='Fácil'),errors:(s[c.id]?.errors||0)+(rate==='Difícil'),difficulty:rate}}));window.App.toast(`Cartão marcado como ${rate}.`,'success');move(1)}
  function filter(value){list=FlashcardsData.filter(c=>!value||c.discipline===value);index=0;flipped=false;render()}
  window.Flashcards={page,init,flip,move,rate,filter};
})();
